name: example
description: Example projects to demonstrate the usage of wolt_modal_sheet library
publish_to: "none"
environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  wolt_responsive_layout_grid: ^0.0.2
  demo_ui_components:
    path: ../demo_ui_components

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
