name: playground
description: A playground to test various use cases with the wolt modal sheet
publish_to: "none"
environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  wolt_modal_sheet:
    path: ..
  demo_ui_components:
    path: ../demo_ui_components
  wolt_responsive_layout_grid: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
