name: check

on:
  # Curently, this workflow is triggered by pull request events only.
  # Uncomment the following line to run this workflow on push events
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2' # Uses the minimum supported version.
          channel: 'stable'
      # Setup Melos
      - name: Setup Melos
        run: |
          pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      # Get Flutter version
      - name: Get Flutter version
        run: flutter --version
      # Get dependencies
      - name: Get dependencies
        run: flutter pub get
      # Run flutter analyze
      - name: flutter analyze
        run: flutter analyze
